apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: argo-cd.packages.kadras.io.2.4.12
spec:
  licenses:
  - Apache 2.0
  refName: argo-cd.packages.kadras.io
  releaseNotes: https://github.com/argoproj/argo-cd/releases
  releasedAt: "2022-09-24T17:52:23Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/arktonix/package-for-argo-cd@sha256:d9aefd2d161c82ac0b6efc0e6bf3abce78c9be31aeca07d12787c5f6b8ded948
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        namespace:
          default: argocd
          description: The namespace where to install Argo CD
          type: string
        service:
          additionalProperties: false
          description: Service configuration for the Argo CD Server
          properties:
            type:
              default: ClusterIP
              description: The Service type for the Argo CD Server
              type: string
          type: object
      type: object
  version: 2.4.12
